# Generated by Django 5.0.3 on 2024-03-12 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0007_remove_shipparts_workpack'),
        ('workPack', '0002_workpack_level_workpack_lft_workpack_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpack',
            name='parts',
            field=models.ManyToManyField(blank=True, to='parts.shipparts'),
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('days_required', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('workPack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workPack.workpack')),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source', to='workPack.node')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target', to='workPack.node')),
            ],
        ),
    ]
