# Generated by Django 5.0.2 on 2024-03-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workPack', '0004_alter_node_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpack',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
