# Generated by Django 5.0.2 on 2024-03-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workPack', '0005_workpack_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpack',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
