# Generated by Django 5.0.2 on 2024-03-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workPack', '0006_alter_workpack_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpack',
            name='days',
            field=models.IntegerField(default=0),
        ),
    ]
