// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package part

import (
	"shipmgr/api/part"
)

type ControllerV1 struct{}

func NewV1() part.IPartV1 {
	return &ControllerV1{}
}
