# Generated by Django 5.0.2 on 2024-02-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startWith', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='shipparts',
            name='isSingle',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shipparts',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shipparts',
            name='statusIndex',
            field=models.IntegerField(default=0),
        ),
    ]
