# Generated by Django 5.0.2 on 2024-03-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_buildhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildhistory',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
