# Generated by Django 5.0.2 on 2024-03-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_alter_buildhistory_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildhistory',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
