# Generated by Django 5.0.3 on 2024-03-12 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_buildhistory_memo'),
        ('workPack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipparts',
            name='workPack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workPack.workpack'),
        ),
    ]
