# Generated by Django 5.0.3 on 2024-03-12 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0006_shipparts_workpack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipparts',
            name='workPack',
        ),
    ]
